### ISSUE TITLE
Are there still any plans to upload the code?

### ISSUE THREAD

**Issue by yifr** [djcrw/generalising-structural-knowledge#1]
Hi! 

I really enjoyed reading this paper! I'm completing an honors thesis on the hippocampal-entorhinal circuit and ML, and the ideas you presented really stood out to me. I was hoping to play around with the code to better understand the model you created. Is releasing the code still a possibility?

Best,
Yoni

**Comment by tfburns** [comment]
Ditto on this. I'm reviewing this paper more in-depth and the code should really be released and available for scrutiny.

**Comment by tfburns** [comment]
Thanks for uploading the code!

**Comment by djcrw** [comment]
All done :)
